databases:
  - name: smartstat
    plan: free
    databaseName: smartstatdb
    user: admin

services:
  - type: web
    plan: free
    name: SmartStat
    region: frankfurt
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn statalysis.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: smartstat
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4